### PR TITLE
Support for FreeBSD

### PR DESCRIPTION
**Pull request by urosgruber**
CPU is not fully supported as library used have a few bugs. Until this is fixed I can force CPU value to be set to "1". #38

### CODE REVIEW

**Comment by urosgruber** [comment]
New version off gopsutil was released with proper CPU reading so everything should be ok. Let me know if anything else is needed to merge this.

**Comment by dch** [comment]
+1 for merging this - any news datadoggers?

**Comment by 0x6e6562** [comment]
+1 for BSD support

**Comment by djmitche** [comment]
(closing this as stale -- we can consult this PR if we decide to go this direction)

**Comment by lgadalla-impinj** [comment]
+1

**Pull request closed without merging**
